<!-- Scripts and Stylesheets -->
<script src="https://use.fontawesome.com/db0b0cbba9.js"></script>
<link rel="stylesheet" href="css/footer.css">
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@500;600&family=Lato:wght@700&family=Dancing+Script:wght@500&family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">

<!-- Footer -->
<footer class="footer">
  <div class="container-fluid container-fluid-custom">
    <!-- First Row -->
    <div class="row row-cols-3">
      <div class="col-sm start">
        <a href="index.php"><img class="responsive" src="images/logo.png" alt="OwnGalaxyLogo" height=98px width="302px"></a>
        <div id="social">
          <a href="https://www.facebook.com/offical.owngalaxy.5"> <i class="fa fa-facebook" aria-hidden="true"></i></a>
          <a href="https://www.instagram.com/official_owngalaxy"> <i class="fa fa-instagram" aria-hidden="true"></i></a>
          <a href="https://www.linkedin.com/in/own-galaxy-2ba4681b4/"> <i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
          <a href="https://twitter.com/own_galaxy"> <i class="fa fa-twitter" aria-hidden="true"></i></a>
          <a href="https://api.whatsapp.com/send?phone=917477212251&text=Hello%20Own%20Galaxy&source=&data=&app_absent="> <i class="fa fa-whatsapp" aria-hidden="true"></i> </a>
        </div>
      </div>
      <div class="col-sm-4 align-self-center row-height">
        <span class="heading">What's Own Galaxy?</span>
        <br>
        <span class="forewords">
          <br>
          <p>Own Galaxy is based on the idea that every individual should know that <em>you deserve every bit of this galaxy.</em></p>
          <br>
        </span>
        <div class="col-sm align-self-center">
          <span class="address"><i class="fa fa-map-marker" aria-hidden="true"></i> &nbsp <bold>Raipur, India (492001)</bold></span>
        </div>
        <div class="col-sm align-self-center">
          <span class="email"><i class="fa fa-envelope" aria-hidden="true"></i> &nbsp <em> customercare.owngalaxy@gmail.com </em></span>
        </div>
      </div>
      <div class="col-sm row-height">
        <br>
        <span class="links" id="links">USEFUL LINKS</span>
        <div class="col-sm links">
          <br>
          <a href="about">ABOUT US</a><br>
          <a href="contact">CONTACT US</a><br>
          <a href="work">WORK WITH US</a><br>
          <a href="privacy">PRIVACY</a><br>
          <a href="privacy">TERMS</a><br>
          <a href="faq">FAQ</a><br>
          <p></p>
        </div>
      </div>
    </div>
    <br>
  </div>
  <hr style="height:0.05em;border-width:0;color:#eee;background-color:#999">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <span class="copyright">
          <p>Copyright &#169; 2020 <a href="index">OwnGalaxy</a>. Designed By <a href="#">Visitron</a>.</p>
        </span>
      </div>
    </div>
  </div>
</footer>
